AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  gitEventHandler to manage push and stars events coming from git.

Parameters:
  slackUrl:
    Type: String
    Description: your Slack Webhook Url.
    Default: ""
Globals:
  Function:
    Timeout: 3
    MemorySize: 128

Resources:
  GitEventHandler:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: src/
      Handler: app.lambda_handler
      Runtime: python3.9
      Environment:
        Variables:
          SLACK_WEBHOOK: !Ref slackUrl
      Events:
        GitEvents:
          Type: HttpApi 
          Properties:
            Path: /
            Method: POST

Outputs:
  StackName:
    Description: "The stack name"
    Value: !Ref AWS::StackName
  GitEventHandlerApi:
    Description: "API Gateway endpoint URL for Prod stage for GitEventHandler to provide to github webhook"
    Value: !Sub "https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com/"
  GitEventHandler:
    Description: "Lambda Function ARN"
    Value: !GetAtt GitEventHandler.Arn
  GitEventHandlerIamRole:
    Description: "Implicit IAM Role created for the function"
    Value: !GetAtt GitEventHandlerRole.Arn
